/*
 Do not edit this file
*/
#include "Score.h"

using namespace OOP;

Score::Score(int id, int score) {
    this->id = id;
    this->score = score;
}
int Score::getID() {
    return id;
}
int Score::getScore() {
    return score;
}