/*
 Do not edit this file
*/
#include "Student.h"

using namespace OOP;

Student::Student(int id, string name) {
    this->id = id;
    this-> name = name;
}
int Student::getID() {
    return id;
}
string Student::getName() {
    return name;
}
